export const testimonials = [
    {
        name: 'Bipin Bakshi',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768594880/first_nv2dqp.jpg',
        text: 'Removed Fake Account Of Senior Military Officer In Just hours',
        avatar: 'BB',
        year: 2025,
    },
    {
        name: 'Psi Anmol Jadhav',
        videoUrl: 'https://res.cloudinary.com/dqqq1vrba/video/upload/v1768594880/second_lasp81.mp4',
        text: 'Removed Fake Account  of Maharashtra Police In 5 minutes',
        avatar: 'PA',
        year: 2025,
    },
    {
        name: 'Raut',
        videoUrl: 'https://res.cloudinary.com/dqqq1vrba/video/upload/v1768594887/third_vryecc.mp4',
        text: 'Recovered Hacked WhatsApp Account in  Just 20 Minutes',
        avatar: 'R',
        year: 2025,
    },
    {
        name: 'ISAC Foundation',
        imageUrls: [
            'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768594880/fourth_crg0rp.jpg',
            'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768594880/fifth_uqcfns.jpg',
            
        ],
        
        avatar: 'IF',
        year: 2025,
    },
    {
        name: 'Prisha Sanyal',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224697/img4_wipgnh.jpg',
        text: 'I am extremely grateful for your exceptional service in recovering my permanently disabled account. Your expertise and professionalism are truly impressive, and I am thrilled to have my account back. Thank you for your prompt and efficient assistance. Your work has made a significant difference, and I appreciate the time and effort you invested in resolving my issue.I highly recommend your services to anyone in need of account recovery assistance.',
        avatar: 'PS',
        year: 2025,
    },
    {
        name: 'Mohammad Gilani',
        videoUrl: 'https://res.cloudinary.com/dqqq1vrba/video/upload/v1768224701/vid2_crv9xd.mp4',
        text: 'Outstanding service! My disabled account was recovered within hours. The professionalism and expertise displayed throughout the process were remarkable. Highly recommend to anyone facing account issues.',
        avatar: 'MG',
        year: 2025,
    },
    {
        name: 'Satyanarayana Ravipati',
        videoUrl: 'https://res.cloudinary.com/dqqq1vrba/video/upload/v1768357587/Hi_Sando_Varghese_I_just_wanted_to_express_my_heartfelt_gratitude_for_recovering_my_hacked_What_b33jee.mp4',
        text: 'I just wanted to express my heartfelt gratitude for recovering my hacked WhatsApp account in just a few hours! Your expertise and prompt assistance are truly impressive. Thank you so much for your help! I’m really grateful for your services.',
        avatar: 'SR',
        year: 2025,
    },
    {
        name: 'Bipin Bakshi',
        text: 'Happy to inform Mr Sando, Cyber Crime Intervention Officier(CCIO) helped me to resolve the Fake Profile issue where an impostr had copied my photos, and was contacting my known security persons who were with me in Indian Army or NSG. With his help I was able to correctly report the problem and get the fake account blocked. Thanks to Sando whom I could contact through ISAC Foundation and CopConnect, he did the role of Cyber Crime First Responder. As a senior millitary officer, my profile was beign used for fake messages about some financial dealings, that has been prevented!',
        avatar: 'BB',
        year: 2024,
    },
    {
        name: 'Zishan Shaikh',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224697/img11_fmhq0j.jpg',
        text: 'I just wanted to send a huge thank you! I still can’t believe you recovered my permanently disabled account in just 12 hours. That’s absolutely incredible! You’ve seriously brought me so much happiness. I really appreciate your amazing work!',
        avatar: 'ZS',
        year: 2025,
    },
    {
        name: 'Gauri',
        videoUrl: 'https://res.cloudinary.com/dqqq1vrba/video/upload/v1768224701/vid1_w8zn3n.mp4',
        text: 'I am extremely grateful for the exceptional service provided in recovering my permanently disabled account. The expertise and professionalism demonstrated throughout the process were truly impressive. I am thrilled to have my account back and sincerely appreciate the prompt and efficient assistance received. The time and effort invested in resolving my issue have made a significant difference, and I highly recommend these services to anyone in need of account recovery assistance.',
        avatar: 'G',
        year: 2025,
    },
    {
        name: 'Piyush ',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img14_oorxev.jpg',
        text: 'Huge thanks to Mr Sando Varghese, Cyber Crime Intervention Officer (CCIO) at ISAC Foundation, for helping me recover my hacked WhatsApp account so quickly and efficiently. His expertise and professionalism made the entire process smooth and stress-free. I highly recommend his services to anyone facing similar issues.',
        avatar: 'P',
        year: 2025,
    },
    {
        name: 'Zrdil Sha',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img8_g34de1.jpg',
        text: 'I just wanted to send a huge thank you! I still can’t believe you recovered my permanently disabled account in just 12 hours. That’s absolutely incredible! You’ve seriously brought me so much happiness. I really appreciate your amazing work!',
        avatar: 'ZS',
        year: 2025,
    },
    {
        name: 'Anna Rose',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img10_swrwii.jpg',
        text: 'thank you so much for recovering my permanently disabled account. I am beyond grateful for your expertise and professionalism throughout the process. Having my account back means the world to me, and I truly appreciate your prompt and efficient assistance. Your dedication and effort have made a significant difference, and I highly recommend your services to anyone in need of account recovery assistance.',
        avatar: 'AR',
        year: 2025,
    },
    {
        name: 'Neha Deshmukh',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224697/img12_ujhejr.jpg',
        text: 'Sando Varghese Bhaiya is amazing! He recovered my permanently disabled account in just 12 hours. I am so grateful for his expertise and professionalism throughout the process. Having my account back means the world to me, and I truly appreciate his prompt and efficient assistance.',
        avatar: 'ND',
        year: 2025,
    },
    {
        name: 'Annu Khanna',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img16_jbs66x.jpg',
        text: 'thank you so much for recovering my permanently disabled account. I am beyond grateful for your expertise and professionalism throughout the process. Having my account back means the world to me.',
        avatar: 'AK',
        year: 2025,
    },
    {
        name: 'C Mon',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img15_v6yccd.jpg',
        text: 'He recovered my permanently disabled account in just 12 hours. thanks a lot bro',
        avatar: 'CM',
        year: 2025,
    },
    {
        name: 'Isika',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224698/img9_nb2dwy.jpg',
        text: 'help me to recover my permanently disabled account in within an hour. thanks a lot bro',
        avatar: 'I',
        year: 2025,
    },
    {
        name: 'Mshahana Kuttippuram',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img8_g34de1.jpg',
        text: 'Incredible recovery service! Lost access to my account but got it back thanks to the expert assistance. Fast, reliable, and trustworthy. Thank you for saving my digital presence!',
        avatar: 'MK',
        year: 2025,
    },
    {
        name: 'Dimple Kumawat',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224698/img7_gr7yf8.jpg',
        text: 'Exceptional work! My permanently disabled account was recovered smoothly. The dedication and technical skills were impressive. Forever grateful for bringing back my digital identity!',
        avatar: 'DK',
        year: 2025,
    },
    {
        name: 'Ansh',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224699/img17_ezs8cl.jpg',
        text: 'Amazing experience! Thought my account was gone forever, but the recovery was swift and successful. Professional service with excellent communication throughout. Truly recommended!',
        avatar: 'A',
        year: 2025,
    },
    {
        name: 'Simran Seth',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224700/img18_tnqbae.jpg',
        text: 'Brilliant service! Account recovery completed efficiently and professionally. The expertise shown was top-notch. Would definitely recommend to anyone facing similar issues. Thank you so much!',
        avatar: 'SS',
        year: 2025,
    },
    {
        name: 'Unknown User',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224697/img1_gzjrpe.jpg',
        text: 'I’m thrilled to share my experience with Mr. Sando Varghese, a WhatsApp recovery specialist who helped me regain access to my hacked account. After falling victim to a hacking incident, I was introduced to Mr. Varghese by a friend, and I’m grateful for the recommendation.Once again, I’d like to express my gratitude to Mr. Sando Varghese for his outstanding support. His expertise has saved me from potential harassment and identity theft. If you’re looking for a reliable WhatsApp recovery specialist, look no further than Mr. Sando Varghese. @kowork.co.in',
        avatar: 'UU',
        year: 2025,
    },
    {
        name: 'Unknown User',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224698/img13_eyo7fg.jpg',
        text: 'I’m thrilled to share my experience with Mr. Sando Varghese, a WhatsApp recovery specialist who helped me regain access to my hacked account. After falling victim to a hacking incident, I was introduced to Mr. Varghese by a friend, and I’m grateful for the recommendation. Once again, I’d like to express my gratitude to Mr. Sando Varghese for his outstanding support. His expertise has saved me from potential harassment and identity theft. If you’re looking for a reliable WhatsApp recovery specialist, look no further than Mr. Sando Varghese. @kowork.co.in',
        avatar: 'UU',
        year: 2025,
    },
    {
        name: 'Kowork.co.im',
        text: 'I\'m thrilled to share my experience with Mr Sando Varghese, a WhatsApp recovery specialist who helped me regain acess to my hacked account. After falling victim to a hacking incident, I was introduced to Mr Sando Varghese through a trusted source. His professionalism, expertise, and dedication were evident from our first interaction. He guided me through the recovery process with patience and clarity, ensuring I understood each step. Thanks to his efforts, I successfully regained access to my WhatsApp account without any data loss. I highly recommend Mr Sando Varghese by a friend, and I\'m grateful for the recommendation that led me to his exceptional services. His expertise has saved me from potential harassment and identify theft. If you\'re looking for a reliable and skilled professional to assist with WhatsApp recovery, Mr Sando Varghese is the person to contact.',
        avatar: 'KC',
        year: 2024,
    },
    {
        name: 'Raj Patel',
        text: 'Yesterday evening, I received a message from a friend asking me to forward a six-digit SMS code via WhatsApp. I complied-and that was all it took for my account to be hacked. I was locked out and unable to generate new codes, while calls and texts continued going out from my number. By this morning, nearly a dozen friends had called me in confusion, and I had to tell them not to answer or forward anything from my account. Then with a reference I approached ISAC CCIO Mr Sando Varghese. He Solved my issue at the earliest. I am a Senior Citizen and not well versed with WhatsApp issues. But Mr Sando Varghese made it so simple for me and recovered my WhatsApp account without any data loss. I am very grateful to him and ISAC Foundation for their support.',
        avatar: 'RP',
        year: 2025,
    },
    {
        name: 'Vinay Chandra',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224697/img5_c4tkwm.jpg',
        text: 'Superb recovery service! Got my disabled account back within a day. The process was transparent and the results exceeded expectations. Highly professional and reliable.',
        avatar: 'VC',
        year: 2025,
    },
    {
        name: 'Saroja Lokesh',
        text: 'I am extremely grateful to Mr. Sando Varghese for his quick and professional support in recovering my hacked WhatsApp account. The issue was resolved within just 10 minutes, which truly reflects his expertise and efficiency. His prompt response and strong knowledge in cyber recovery made the entire process smooth and stress-free. Mr. Sando Varghese is a reliable recovery specialist and a great support for anyone facing cyber-related issues.',
        avatar: 'SL',
        year: 2025,
    },
    {
        name: 'Kriti Amin',
        imageUrl: 'https://res.cloudinary.com/dqqq1vrba/image/upload/v1768224698/img6_uk9inc.jpg',
        text: 'Fantastic work! My account was recovered quickly and securely. The support provided was exceptional with clear guidance throughout. Extremely satisfied with the service.',
        avatar: 'KA',
        year: 2025,
    }
];